version: '3'


services:
  web:
    ports:
      - 8080:80
    build: .
    volumes:
      - ./www.conf:/etc/php8/php-fpm.d/www.conf:ro
      - ./start-fpm.sh:/docker-entrypoint.d/05-start-fpm.sh:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro